# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Rui Li
tagline:             'M.Sc. student in Computer Science'
description:         Ultimately there's only definitions. -- Dr. Yongyi Mao
baseurl:             'https://github.com/leereborn/rui-li/tree/master'
paginate:            5

# About
author:
  name:              Rui Li
  portrait:          '/assets/images/img_about.jpg'
  resume:            '/assets/resume.pdf'

# Index
home_picture: 'assets/images/img_home.jpg'

# Projects
projects:
  - name: Android Chat App
    url: https://github.com/leereborn/Android-chat-room
  
  - name: Facial Age and Gender Detection
    url: https://github.com/leereborn/Age-Gender-Classification-CNN

  - name: Connection between Adversarial Training and Regularization
    url: https://github.com/leereborn/adv-vs-reg

# Build settings
plugins:
  - jekyll-paginate